### ISSUE TITLE
Misconfigured repositories file location when using Helm 3.0.2

### ISSUE THREAD

**Issue by Airwise** [hypnoglow/helm-s3#103]
Using s3 plugin version 0.9.0 with Helm 3.0.2 and I'm running into an issue.  The plugin appears to be looking for the repository config file at a location different from where helm 3.0.2 stores it.
e.g.  s3 push results in:
```
load repo file: Couldn't load repositories file (/var/lib/jenkins/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
```
Meanwhile running helm env results in:
```
HELM_NAMESPACE="default"
HELM_KUBECONTEXT=""
HELM_BIN="/usr/local/bin/helm"
HELM_DEBUG="false"
HELM_PLUGINS="/var/lib/jenkins/.local/share/helm/plugins"
HELM_REGISTRY_CONFIG="/var/lib/jenkins/.config/helm/registry.json"
HELM_REPOSITORY_CACHE="/var/lib/jenkins/.cache/helm/repository"
HELM_REPOSITORY_CONFIG="/var/lib/jenkins/.config/helm/repositories.yaml"
```
Note the difference in form .../.helm/repository/repositories.yaml vs .../.config/helm/repositories.yaml

**Comment by hypnoglow** [comment]
Hi! It seems that the plugin detects Helm v2 for your case, as the error shows. Can you please check the env var `TILLER_HOST` value? Probably you are using Helm v3 binary but for some reason this env var is defined in your CI settings and the plugin thinks it is Helm v2.

**Comment by cablespaghetti** [comment]
@Airwise Are you using Alpine Linux? I can't get it to happen on my laptop but it's happening in our build containers which run Alpine. I wonder if for some reason Go's environment variable logic is different on Alpine...

**Comment by cablespaghetti** [comment]
To be specific it seems to work on Alpine 3.10 but not Alpine 3.9 from very limited testing.

**Comment by cablespaghetti** [comment]
Ok I take it back. It works on Alpine 3.9 but not on our Alpine 3.9 build image I have no clue why.

**Comment by Airwise** [comment]
Hi, Hypnoglow!  Sorry I let this linger a few days.  Busy, busy!
It looks like TILLER_HOST is unset:
```
[ec2-user@ip-10-206-80-144 ~]$ sudo -ujenkins bash
bash-4.2$ echo $TILLER_HOST

bash-4.2$ exit
```
Also this is a brand new jenkins server and helm 3.0.2 is the first/only version of helm that I've installed on it.

Is TILLER_HOST the way plugin decides which version of helm is running?

Thanks for engaging!

**Comment by Airwise** [comment]
@cablespaghetti FWIW I'm using helm directly from our jenkins server.  I.e. Not running helm from within a container.  Sorry, that probably doesn't help you with your issues.

**Comment by hypnoglow** [comment]
I've tuned Helm version detection and also added the way to force the mode if the detection still fails for any reason. You can now set environment variable `HELM_S3_MODE=3` to force the plugin operate in Helm v3 mode.

This change lands in v0.9.1 plugin release.

Please try it out, I hope this helps!

**Comment by Airwise** [comment]
Thanks @hypnoglow!  That sounds perfect.  Unfortunately it looks like the checksum for v 0.9.1 is invalid.  (Or at least helm thinks so...)
```
$ helm plugin install https://github.com/hypnoglow/helm-s3.git
Downloading and installing helm-s3 v0.9.1 ...
Invalid checksum
helm-s3 install hook failed. Please remove the plugin using 'helm plugin remove s3' and install again.
Error: plugin install hook for "s3" exited with error
```

**Comment by hypnoglow** [comment]
There was a problem with goreleaser, should be fixed now, please try again!

**Comment by Airwise** [comment]
So I think we got further.  Now the plugin is complaining about the repo file so I'm guessing it found it.  I think the go structure may have declared "repositories" to be a string type, but it appears to be an array (at least in the yaml).

```
bash-4.2$ /usr/local/bin/helm repo ls
NAME                    URL
modo-helm-charts        s3://modo-helm-charts
bash-4.2$ cat /var/lib/jenkins/.config/helm/repositories.yaml
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  keyFile: ""
  name: modo-helm-charts
  password: ""
  url: s3://modo-helm-charts
  username: ""
bash-4.2$ HELM_S3_MODE=3 /usr/local/bin/helm s3 push ./api-checkout-rc-1.1.0.tgz modo-helm-charts
load repo file: error unmarshaling JSON: json: cannot unmarshal array into Go value of type string
Error: plugin "s3" exited with error
```

**Comment by hypnoglow** [comment]
I think the main issue is that `apiVersion` is empty in this file. Can you please try remove this file and add your repo again?

**Comment by Airwise** [comment]
Well, I've tried removing and adding repos a bunch of times, not just an s3 repo, but https://kubernetes-charts.storage.googleapis.com/ as well.  That apiVersion field never gets populated.

I've also tried manually putting "v1" in that field and it doesn't change anything.  I still git the json.Unmarshaling error

I looked through your code and it looks like you aren't ever directly unmarshaling json into a go structure (just byte slices) so I'm kind of at a loss as to where this error is coming from.  I guess the helm code itself?

Kinda weird.

**Comment by hypnoglow** [comment]
Yep, weird.

I tried to at least reproduce the error.

I took you repo file:

```yaml
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
  - caFile: ""
    certFile: ""
    keyFile: ""
    name: modo-helm-charts
    password: ""
    url: s3://modo-helm-charts
    username: ""
```

And wrote a simple test:

```go
import (
        // ...

	helm3_repo "helm.sh/helm/v3/pkg/repo"
	helm2_repo "k8s.io/helm/pkg/repo"
)

func TestLoad(t *testing.T) {
	setupHelm2()
	setupHelm3()

	_, err := helm3_repo.LoadFile("testdata/repo.yaml")
	require.NoError(t, err) // OK

	_, err = helm2_repo.LoadRepositoriesFile("testdata/repo.yaml")
	require.NoError(t, err) // FAILS
}

```

Failure:

```
        	Error:      	Received unexpected error:
        	            	error unmarshaling JSON: json: cannot unmarshal array into Go value of type string
        	Test:       	TestLoad
```

Seems like error you got.

But fixing the file with version also fixes the test, resulting in no error:

```yaml
apiVersion: "v1"
generated: "0001-01-01T00:00:00Z"
repositories:
  - caFile: ""
    certFile: ""
    keyFile: ""
    name: modo-helm-charts
    password: ""
    url: s3://modo-helm-charts
    username: ""
```

So it is still unclear for me if it ever tries to load the file using old sdk, or the repo file is nevertheless corrupted, or something else happening.

**Comment by Airwise** [comment]
Well, thanks for trying!  I'll try to bang on it some more as I have time.  Out of curiosity what version of helm are you using?  3.0.2?

**Comment by hypnoglow** [comment]
> Out of curiosity what version of helm are you using? 3.0.2?

Yep, locally I have both 3.0.2 and 2.16.1

**Comment by allamand** [comment]
I've got the same issue with 3.0.2. It works locally, but it fails in my CI pipeline, and I can't figure out why. The CI env is fresh, and I just install helm3 and the plugin from nothing

```
$ helm env
...
HELM_REPOSITORY_CONFIG="/root/.config/helm/repositories.yaml"

$ helm s3 push s3/capi-0.0.1.tgz capi --force
load repo file: Couldn't load repositories file (/root/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
```

**Comment by alexxed** [comment]
I think the [verification of helm version ](https://github.com/hypnoglow/helm-s3/blob/1693ffc8034740866a3c9a809ab8714df654eacb/internal/helmutil/version.go#L32-L40)is too naive. In this case it fails:
helm version --short --client
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/x/.kube/microk8s.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/x/.kube/microk8s.yaml
v3.3.4+ga61ce56

**Comment by juanfe2793** [comment]
In our case it works running the following:

`HELM_S3_MODE=3 helm s3 push my-chart.tgz my-repo`.
