### ISSUE TITLE
Upgrade the Go SDK to support IAM roles for Kubernetes ServiceAccounts

### ISSUE THREAD

**Issue by gopisaba** [hypnoglow/helm-s3#109]
I am trying to install helm s3 plugin in our Jenkins slave pods. I am using [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) to get the S3 permissions but I am seeing access denied when helm try to `PutIndex` or any other S3 operation. [This feature needs Go SDK version](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html) to be `>=1.23.13`. 

Could you please upgrade the Go SDK to support this feature?

**Comment by hypnoglow** [comment]
Thank you for your request! The plugin with upgraded SDK is available in v0.9.2
