### ISSUE TITLE
Error when trying to push package that contains Chart.yaml with 31 dependencies

### ISSUE THREAD

**Issue by tal9543** [hypnoglow/helm-s3#112]
helm client version: v3.0.3
helm s3 version: 0.9.2

when trying to push package  that contains Chart.yaml with 31 dependencies
helm s3 push --force solution.tgz s3-solution-global-charts

Error:
upload chart to s3: upload object to s3: MetadataTooLarge: Your metadata headers exceed the maximum allowed metadata size
	status code: 400, request id: 3F85E2D4089EDF8D, host id: PbCItQ4IsQKAEPi35LrM2wfrYHyAWwEQhpU/dgnTM7ihumlm4mc2Sq5nsQexQ2mN6+1hgSs+obE=
Error: plugin "s3" exited with error

*I managed to push it with awscli so it was not related to aws limitation.
*with fewer dependencies (i tried with 5) it works..
*the issue is only with the Chart.yaml dependencies list, not with the size of the package

Thank you in advance!

**Comment by hypnoglow** [comment]
Thank you for reporting the issue.

Wow, I've never had a chance to deal with charts with 30+ dependencies :open_mouth:  The issue is pretty straightforward - s3 custom metadata limit is 2kb, so probably your chart meta exceeds this limit.

I don't think I'm able to suggest any easy solution for this right now. We use s3 metadata to store chart meta to make some operations more lightweight. Probably we can revisit this concept, making metadata feature optional and describe consequences.

**Comment by tal9543** [comment]
Thank you for your fast reply!
for now, I managed to workaround it with:
push with awscli 
and then I reindex with helm-s3 command

**Comment by hypnoglow** [comment]
I thought that reindex also throws this error, because it also writes chart meta to metadata :/ Glad that worked for you.

**Comment by cep21** [comment]
Also having this issue, at 20 dependencies.

**Comment by rafalwrzeszcz** [comment]
The problem appears I think after switching to Helm3. Helm2 did not store dependencies in chart metadata. Maybe it's possible to exclude dependencies form metadata? Everything worked with Helm2 so dependencies we do not need in metadata on S3.

**Comment by jroucheton** [comment]
I am facing the same issue after switching from helm v2 to v3.

**Comment by ericmcbride** [comment]
facing the same issue

**Comment by DavidARivkin** [comment]
Yes, this is blocking our progress. If anyone has a great work-around suggestion or other change they can suggest, not to mention an ETA for this getting fixed, it would be appreciated.

**Comment by hypnoglow** [comment]
The plugin version 0.10.0 is released.
