### ISSUE TITLE
Parallel installation of Helm v2 and v3 causes plugin to fail with apiVersion error

### ISSUE THREAD

**Issue by stephan2012** [hypnoglow/helm-s3#118]
On my system, Helm v2 and v3 are both installed (Helm v2 as `/usr/local/bin/helm`, Helm v3 as `/usr/local/bin/helm3`) for compatibility reasons. This causes the S3 plugin to fail:

```
$ helm3 s3 push --ignore-if-exists my-chart-0.1.15.tgz myrepo
failed to load chart file: apiVersion 'v2' is not valid. The value must be "v1"
Error: plugin "s3" exited with error
```

Looks like the plugin does not pick the right version.

**Comment by stephan2012** [comment]
Right, seems to be hardcoded… https://github.com/hypnoglow/helm-s3/blob/d65cc1dd9c416f28ec1382757cb682472ef9bf30/internal/helmutil/version.go#L32

Does Helm pass anything that could help identifying the right binary? Otherwise, could an environment variable be an option to specifiy the desired Helm executable?

**Comment by ddcprg** [comment]
I'm experiencing this same issue and I only have Helm v3.3.4 and S3 plugin v0.10.0 installed

**Comment by joosangkim** [comment]
I'm also experiencing same issue. My environment is Helm v3.4.1 and S3 plugin v0.10.0.

**Comment by jpke** [comment]
> I'm also experiencing same issue. My environment is Helm v3.4.1 and S3 plugin v0.10.0.

does it work if you add `HELM_S3_MODE=3` before your helm s3 call?

**Comment by excavador** [comment]
Met the same problem
HELM_S3_MODE=3 helped

**Comment by stephan2012** [comment]
Looks like setting `HELM_S3_MODE=3` solves this issue. However, for me it is no longer of any relevance since we have migrated all deployments to Helm v3 meanwhile so I will close it.
