### ISSUE TITLE
Unable to search repository

### ISSUE THREAD

**Issue by ddcprg** [hypnoglow/helm-s3#119]
It seems like helm is not able to search in S3 repositories. I have a S3 repo configured and I've initialised it with the plugin and pushed some charts. I can push, delete, reindex, install charts but the search is not working and always returns "No results found"

```
$> helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
$> helm plugin list
NAME	VERSION	DESCRIPTION
diff	3.1.1  	Preview helm upgrade changes as a diff
s3  	0.9.2  	The plugin allows to use s3 protocol to upload, fetch charts and to work with repositori...
$> helm search repo test
No results found
```

This happens when we use SEMVER with pre-release tags, e.g. 0.0.1-abcdefg

**Comment by JohnnyBeProgramming** [comment]
I am having similar issues. In my case, I only see `v1` charts listed when doing a search. 
The `v2` charts are not being listed, even though they got pushed and are indexed.
```
 - apiVersion: v2  # <-- Not showing in a search
```

**Comment by hypnoglow** [comment]
@ddcprg 

Try adding `--devel` flag to `helm search repo`. 

```
$ helm search repo hypnoglow --versions --devel
NAME                                	CHART VERSION	APP VERSION	DESCRIPTION
hypnoglow-charts/h3-rel-foo1	0.1.0        	1.16.0     	A Helm chart for Kubernetes
hypnoglow-charts/h3-rel-foo1	0.0.1-alpha.1	1.16.0     	A Helm chart for Kubernetes
hypnoglow-charts/h3-ver       	0.0.1-alpha.1	1.16.0     	A Helm chart for Kubernetes
```

@JohnnyBeProgramming Do you have a reproducer? I tested it, and it works fine for charts with `apiVersion: v2` as shown above.
