### ISSUE TITLE
Reject the push if the version is already on S3

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [hypnoglow/helm-s3#13]
I think that the push should be rejected if the version is already there.
Maybe a `strict` flag if this not what you want by default?

In addition if i push the same version the index file doesn't overrides the old one.

**Comment by hypnoglow** [comment]
Hi @SharpEdgeMarshall !

>I think that the push should be rejected if the version is already there.

Can you please describe your use case where you need to reject the push attempt on existing version?

>In addition if i push the same version the index file doesn't overrides the old one.

I'm going to investigate this and respond after.

**Comment by SharpEdgeMarshall** [comment]
Use case is CI automated pushing of charts packages, if someone forget to bump chart version the package is overwritten.
This could potentially cause issue in production if a deploy of the application is made after.
The best solution i could think is a `--force` flag to replace the package if already present.

**Comment by hypnoglow** [comment]
As I investigated, Helm maintainers [adhere to the idea of immutable charts](https://github.com/kubernetes/helm/issues/3084). So I think your proposal makes sense, with a `--force` flag implementation.

Let me think a bit more about it. If I will not find any reason against, I will implement it.

**Comment by markhu** [comment]
I agree, unless there is a -SNAPSHOT suffix.

**Comment by andrewlock** [comment]
+1 for this proposal, I just ran into an issue because of exactly this situation

**Comment by hypnoglow** [comment]
I think `--replace` is the most suitable name for a flag since it explicitly declares the intent.

So the implementation works as follows:

```
$ helm s3 push /tmp/foobar-0.5.2.tgz hypnoglow
The chart already exists in the repository and cannot be overwritten without an explicit intent. If you want to replace existing chart, use --replace flag:

	helm s3 push --replace /tmp/foobar-0.5.2.tgz hypnoglow

Error: plugin "s3" exited with error
```

What do you think?

---

> I agree, unless there is a -SNAPSHOT suffix.

I'm not sure if we need to treat some specific versions in another way. I mean, I think the plugin should be agnostic to the filename/version.

**Comment by andrewlock** [comment]
Looks good to me 👍 

> I'm not sure if we need to treat some specific versions in another way. I mean, I think the plugin should be agnostic to the filename/version.

I agree, the decision to replace or not should be made external to the plugin

**Comment by SharpEdgeMarshall** [comment]
I think that `--force` is a better naming because is consistent with other tools and doesn't assume there is a version to replace like `--replace` instead do.

**Comment by hypnoglow** [comment]
@SharpEdgeMarshall You convinced me, let it be `--force` :ok_hand:

**Comment by hypnoglow** [comment]
Version [0.6.0](https://github.com/hypnoglow/helm-s3/releases/tag/v0.6.0) is released with this feature implemented :tada:, so I'm closing this issue. Feel free to open a new issue if something goes wrong
