### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by dallasmarlow** [hypnoglow/helm-s3#130]
The install script used by helm to download this plugin assumes an AMD64 arch for all linux hosts. Ideally an ARM64 arch release could be added, but the install should fail on ARM64 hosts if not supported.

**Comment by jaydp17** [comment]
+1 an out of the box linux/arm64 support would be nice.
Currently, we're building it from source & it works fine.

**Comment by hypnoglow** [comment]
Will be available in v0.13.0 released today.
