### ISSUE TITLE
Allow reindex with a non-S3 URL

### ISSUE THREAD

**Issue by colearendt** [hypnoglow/helm-s3#133]
https://github.com/hypnoglow/helm-s3/blob/d20d0fae58a750e055c5d90eaaf9da1dfcfdd98f/cmd/helms3/reindex.go#L38

Perhaps this is an anti-pattern, but if an S3 bucket is to be accessed publicly via CloudFront (i.e. HTTP), it would be nice to be able to manage it via `helm s3`, but provide a different URL. I propose implementing a `--url` parameter for the `reindex` command, much like `helm repo index`.

```
# proposed
helm s3 reindex s3://my-bucket/charts/ --url=https://my.cdn.com/charts/
```

**Comment by almson** [comment]
Isn't this what `--relative` is for?

**Comment by hypnoglow** [comment]
For anyone looking into this, the solution is to use [`--relative` flag](https://github.com/hypnoglow/helm-s3#relative-chart-urls).
