### ISSUE TITLE
Can't delete relative charts

### ISSUE THREAD

**Issue by markmaxey** [hypnoglow/helm-s3#134]
`helm s3 delete` doesn't work when a chart was pushed using the `helm s3 push --relative` because [idx.Delete(act.name, act.version)](https://github.com/hypnoglow/helm-s3/blob/d65cc1dd9c416f28ec1382757cb682472ef9bf30/cmd/helms3/delete.go#L42) returns the [relative URL](https://github.com/hypnoglow/helm-s3/blob/d65cc1dd9c416f28ec1382757cb682472ef9bf30/internal/helmutil/index_v2.go#L106) producing the following error: `delete chart file from s3: chart foo-1.0.0.tgz protocol is not s3`.

While the S3 bucket I'm using is not replicated, it is exposed as a static HTTP website because Helm repository UIs like Rancher's doesn't support the `s3://` protocol thus requiring `--relative` URLs.

**Comment by avidspartan1** [comment]
I'm also seeing this behavior when trying to use an S3 repo.
