### ISSUE TITLE
Index global generated timestamp not updated

### ISSUE THREAD

**Issue by josephprem** [hypnoglow/helm-s3#142]
When we push new charts , the chart is indexed correctly  with the correct timestamp, however the global **generated** field is never updated in index.yaml
 generated: "2021-03-22T16:50:57.223376384Z"

Raising this issue since we have systems that does intelligent cache based on index.yaml  generated timestamp.  Jfrog Artifactory helm repo, Harbor helm repos  update this field everytime the index.yaml is modified

**Comment by hypnoglow** [comment]
Should be fixed by https://github.com/hypnoglow/helm-s3/pull/149

**Comment by hypnoglow** [comment]
Should be fixed by: https://github.com/hypnoglow/helm-s3/pull/325
