### ISSUE TITLE
The execution of install.sh with helm plugin install helm-s3 fails under alpine images

### ISSUE THREAD

**Issue by jamesjsanders** [hypnoglow/helm-s3#152]
## Issue 
The if statement in install.sh utilizing `which` command fails to check the binary path for `wget`, `curl`, `sha256sum`, and `openssl` binaries when utilizing Alpine images.

## Helm plugin install error 

Command: `helm plugin install https://github.com/hypnoglow/helm-s3.git`

## Software version and run
```
docker run -it a260cbf686cf /bin/bash

bash-5.1# uname -a
Linux 82377b20a6a8 4.15.0-1027-gcp #28~16.04.1-Ubuntu SMP Fri Jan 18 10:10:51 UTC 2019 x86_64 Linux

bash-5.1# helm plugin list
NAME    VERSION DESCRIPTION

bash-5.1# helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}


bash-5.1# which -a
BusyBox v1.33.1 () multi-call binary.

Usage: which COMMAND...

Locate COMMAND


bash-5.1# curl --version
curl 7.78.0 (x86_64-alpine-linux-musl) libcurl/7.78.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 nghttp2/1.43.0
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets


bash-5.1# which curl
/usr/bin/curl

bash-5.1# helm plugin install https://github.com/hypnoglow/helm-s3.git
Downloading and installing helm-s3 v0.10.0 ...
ERROR: no curl or wget found to download files.
WARNING: no tool found to verify checksum
tar (child): releases/v0.10.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
helm-s3 install hook failed. Please remove the plugin using 'helm plugin remove s3' and install again.
Error: plugin install hook for "s3" exited with error
```

```
bash-5.1# helm plugin install https://github.com/hypnoglow/helm-s3.git
Downloading and installing helm-s3 v0.10.0 ...
ERROR: no curl or wget found to download files.
WARNING: no tool found to verify checksum
tar (child): releases/v0.10.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
helm-s3 install hook failed. Please remove the plugin using 'helm plugin remove s3' and install again.
Error: plugin install hook for "s3" exited with error
```

## Possible FIx
Updating IF statements from [line 49 in the install.sh](https://github.com/hypnoglow/helm-s3/blob/e208d4e648f9cfef7c68a2753d101ee78a5f7937/hack/install.sh#L49) 

Change if statement condition to check for file **(`-f`)**
```
(
    if [ -f "$(which curl 2>/dev/null)" ]; then
        curl -sSL "${binary_url}" -o "${binary_filename}"
        curl -sSL "${checksum_url}" -o "${checksums_filename}"
    elif [ -f "$(which wget 2>/dev/null)" ]; then
        wget -q "${binary_url}" -O "${binary_filename}"
        wget -q "${checksum_url}" -O "${checksums_filename}"
    else
      echo "ERROR: no curl or wget found to download files." > /dev/stderr
    fi
)

# Verify checksum.
(
    if [ -f "$(which sha256sum 2>/dev/null)" ]; then
        checksum=$(sha256sum ${binary_filename} | awk '{ print $1 }')
        validate_checksum ${checksum} ${checksums_filename}
    elif [ -f "$(which openssl 2>/dev/null)" ]; then
        checksum=$(openssl dgst -sha256 ${binary_filename} | awk '{ print $2 }')
        validate_checksum ${checksum} ${checksums_filename}
    else
        echo "WARNING: no tool found to verify checksum" > /dev/stderr
    fi
)

```

Add an or condition in the IF statement under the **_install.sh_** bash script to support `whereis` commands to pull binary location. 

```
(
    if [ -x "$(which curl 2>/dev/null)" ] || [ -f "$(whereis curl |awk '{print $2}' 2>/dev/null)" ]; then
        curl -sSL "${binary_url}" -o "${binary_filename}"
        curl -sSL "${checksum_url}" -o "${checksums_filename}"
    elif [ -x "$(which wget 2>/dev/null)" ] || [ -f "$(whereis wget |awk '{print $2}' 2>/dev/null)" ]; then
        wget -q "${binary_url}" -O "${binary_filename}"
        wget -q "${checksum_url}" -O "${checksums_filename}"
    else
      echo "ERROR: no curl or wget found to download files." > /dev/stderr
    fi
)

# Verify checksum.
(
    if [ -x "$(which sha256sum 2>/dev/null)" ] || [ -f "$(whereis sha256sum |awk '{print $2}' 2>/dev/null)" ]; then
        checksum=$(sha256sum ${binary_filename} | awk '{ print $1 }')
        validate_checksum ${checksum} ${checksums_filename}
    elif [ -x "$(which openssl 2>/dev/null)" ] || [ -f "$(whereis openssl |awk '{print $2}' 2>/dev/null)" ]; then
        checksum=$(openssl dgst -sha256 ${binary_filename} | awk '{ print $2 }')
        validate_checksum ${checksum} ${checksums_filename}
    else
        echo "WARNING: no tool found to verify checksum" > /dev/stderr
    fi
)
```

**NOTE**: This would require that the user has the **util-linux** package installed (_apk add util-linux_) on the Alpine instance.

**Comment by marandalucas** [comment]
# Issue
I have the same problem building alpine/helm:3.6.3 when It's installing the helm s3 plugin v0.10.0

Dockerfile
`
FROM alpine/helm:3.6.3`
RUN helm plugin install https://github.com/databus23/helm-diff --version
`

`
$ docker build -t helmS3Plugin .

  ..................
  Step 9/10 : RUN helm plugin install https://github.com/hypnoglow/helm-s3 --version v0.10.0
   ---> Running in 250f96e6329d
  Downloading and installing helm-s3 v0.10.0 ...
  ERROR: no curl or wget found to download files.
  WARNING: no tool found to verify checksum
  tar: can't open 'releases/v0.10.0.tar.gz': No such file or directory
  helm-s3 install hook failed. Please remove the plugin using 'helm plugin remove s3' and install again.
  Error: plugin install hook for "s3" exited with error
  The command '/bin/sh -c helm plugin install https://github.com/hypnoglow/helm-s3 --version ${HELM_S3_PLUGIN_VERSION}' returned a non-zero code: 1
`

#jamesjsanders Could you do the pull request to fix this issue, I believe that the first option is good.

# WorkAround

I've made an debian-slim/helm:3.6.3 by my self with helm diff plugin and helm s3 plugin.

**Comment by marandalucas** [comment]
sockmal/helm-hs3-hdiff:3.7.0

**Comment by r4j4h** [comment]
Just wanted to report we ran into this in a pipeline that hadn't been run in a while.

We tried both `alpine3.13` as well as with Docker v20.10.8, and still ran into this error.

After noticing our pipeline was downloading the latest helm-s3 v0.13.0 I noticed these commits semi-recently made to the install.sh script:
- https://github.com/hypnoglow/helm-s3/commit/f560e38745f3313c77ba7ca43ff59b144f2ad95e use command instead of test
- https://github.com/hypnoglow/helm-s3/commit/70cdba9d40af4c68f7c5df8f5e473ecd79a08b35 ISSUE-30 Migrate CLI from kingpin to cobra
And tracked back to see they came in the 0.13.0 release.

I tried pinning helm-s3 to an older version and found it fixed it, both the `alpine3.13` and the newer Docker engine solutions worked. (Without them they still break, of course)

```
helm plugin install https://github.com/hypnoglow/helm-s3.git --version v0.12.0  
```

I do not know a solution to work in 0.13.0 yet, so I wanted to let y'all know this might have regressed in some way

**Comment by Xavientois** [comment]
> I tried pinning helm-s3 to an older version and found it fixed it, both the `alpine3.13` and the newer Docker engine solutions worked. (Without them they still break, of course)
> 
> ```
> helm plugin install https://github.com/hypnoglow/helm-s3.git --version v0.12.0  
> ```
> 
> I do not know a solution to work in 0.13.0 yet, so I wanted to let y'all know this might have regressed in some way

Was experiencing this issue yesterday, but it looks like the release of `v0.14.0` fixed it!
