### ISSUE TITLE
This allows you to have private or public Helm chart repositories hosted on Amazon S3. HOW?

### ISSUE THREAD

**Issue by abhijeetka** [hypnoglow/helm-s3#164]
I am looking to host public helm repository , I tried to go though the documents but unable to get any details .

Any help could be appriciated.

**Comment by hypnoglow** [comment]
Hello @abhijeetka 

I agree that we should have a better documentation for setting up a public repo.

If you want to host your repository in a way the charts in the public bucket can be accessed via HTTP, the solution is to use `--relative` flag when publishing charts.

For `s3://` protocol I believe it should work out of the box, just set up the right permissions.

**Comment by abhijeetka** [comment]
@hypnoglow Thanks, it worked. Now I am able to access it via HTTP protocol.
