### ISSUE TITLE
helm plugin install fails on 0.12.0 with invalid checksum

### ISSUE THREAD

**Issue by mixja** [hypnoglow/helm-s3#190]
As per the title - my environment:

- Mac M1 (ARM)
- Helm version 3.8.2

Installation fails with an error:

```
% helm plugin install https://github.com/hypnoglow/helm-s3.git
Downloading and installing helm-s3 v0.12.0 ...
Invalid checksum
helm-s3 install hook failed. Please remove the plugin using 'helm plugin remove s3' and install again.
```

If I target version 0.11.0 of the plugin installation is fine.

**Comment by hypnoglow** [comment]
Hmm, I double-checked the checksums manually downloading the files from the release page, and everything seems OK.

```
$ sha256sum -c --ignore-missing helm-s3_0.12.0_checksums.txt
helm-s3_0.12.0_darwin_arm64.tar.gz: OK
```

Could you also try to download release and checksum files and verify?

Also the output of `uname -m` and `uname` would be helpful to ensure that the correct arch is selected.

**Comment by hypnoglow** [comment]
We've additionally tested installation on Mac M1 and everything seems to work fine. So we need more details on how to reproduce the problem.

**Comment by KenFigueiredo** [comment]
I'm seeing this same issue on an M1 Mac through an alpine docker build. 
I'm able to reproduce it with this Dockerfile:

```
FROM alpine:3.16.0

RUN apk add --update git curl bash openssl

RUN curl -sL https://git.io/get_helm.sh | bash -s -- --version "v3.9.0" && adduser -h /helm -D helm
RUN helm plugin install https://github.com/hypnoglow/helm-s3.git
```

Error:
```
Step 4/4 : RUN helm plugin install https://github.com/hypnoglow/helm-s3.git
 ---> Running in 6290d04be245
Downloading and installing helm-s3 v0.12.0 ...
Invalid checksum
helm-s3 install hook failed. Please remove the plugin using 'helm plugin remove s3' and install again.
Error: plugin install hook for "s3" exited with error
The command '/bin/sh -c helm plugin install https://github.com/hypnoglow/helm-s3.git' returned a non-zero code: 1
```


Pinning back a version to `0.11.0` seems to resolve it as a work around:
```
helm plugin install https://github.com/hypnoglow/helm-s3.git --version v0.11.0
```

**Comment by hypnoglow** [comment]
I've checked it, and this should be fixed with the latest version or any version starting from v0.13.0.
