### ISSUE TITLE
Bad EOL characters in shell scripts

### ISSUE THREAD

**Issue by tim-ooohtv** [hypnoglow/helm-s3#210]
It seems like the scripts under the `/hack` directory have bad line endings:

```bash
$ uname -a
Linux XXXX 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ helm version
version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}

$ helm plugin install https://github.com/hypnoglow/helm-s3.git
/usr/bin/env: ‘bash\r’: No such file or directory
Error: plugin install hook for "s3" exited with error
```

**Work around**
```bash
git clone https://github.com/hypnoglow/helm-s3
cd helm-s3
dos2unix hack/*.sh
helm plugin install .
```

**Comment by hypnoglow** [comment]
Hi,

Are you sure that the script files were not changed accidentally? It seems that everything is fine with line endings for me. Running commands to convert line endings produces no diff.

**Comment by tim-ooohtv** [comment]
You are right. It seems like my git my `core.autocrlf` was incorrectly set. The following does work for me now (without `dos2unix`)

```bash
git config --global core.autocrlf false
git clone https://github.com/hypnoglow/helm-s3
cd helm-s3
helm plugin install .
```

But for some reason `helm plugin install https://github.com/hypnoglow/helm-s3.git` still fails with the same error. Maybe its a helm thing.
