### ISSUE TITLE
Reindex timeout flag is not documented

### ISSUE THREAD

**Issue by dobriSu** [hypnoglow/helm-s3#218]
Reindex timeout flag is not documented in README.md.
Proposal add to README.md

If you run into error:

```
upload index to the repository: upload index to S3 bucket: RequestCanceled: request context canceled
caused by: context deadline exceeded
Error: plugin "s3" exited with error
```

You can extend reindex execution time with --timeout flag (default 5m):

```bash
helm s3 reindex mynewrepo --timeout 15m
```

**Comment by hypnoglow** [comment]
Thanks for noticing! The documentation should land to the README soon.
