### ISSUE TITLE
helm s3 push fails with an error

### ISSUE THREAD

**Issue by vishnugth** [hypnoglow/helm-s3#221]
⚡️helm s3 push ./halo-demo-chart-0.1.0.tgz test
Error: load repo file: Couldn't load repositories file (/Users/v01/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
Error: plugin "s3" exited with error

when I try to push the package to the s3 bucket using the plugin it fails the above error. I don't see any issues with the aws cli. It is working as expected.

Also, it prints a message to run `helm init` command, which is not available under helm3.

Package versions:

```
⚡️helm version --short
v3.9.4+gdbc6d8e

⚡️helm plugin list

NAME	VERSION	DESCRIPTION
s3  	0.14.0 	Provides AWS S3 protocol support for charts and repos. https://github.com/hypnoglow/helm-s3
```

**Comment by AnakinPt** [comment]
I have the exact same error.
$ helm version --short
v3.10.1+g9f88ccb

$ helm plugin list
NAME    VERSION DESCRIPTION
s3      0.14.0  Provides AWS S3 protocol support for charts and repos. https://github.com/hypnoglow/helm-s3

**Comment by aispringli** [comment]
when i use it on gitlab ci, the probelm must show

**Comment by aispringli** [comment]
i find a reason, i find helm init in helm2 doc, so i guess whether is the version reason, final export HELM_S3_MODE=3, now it work well. the probelm is so beyond logic and above reason. hope whe auther can solve it.

**Comment by hypnoglow** [comment]
As mentioned, you can use HELM_S3_MODE to force Helm v3 in case of problems.

Also, a [bug was fixed](https://github.com/hypnoglow/helm-s3/pull/269) recently that might caused the problem.

I'm going to close this, please open a new issue if the problem persists after the v0.16.0 release.
