### ISSUE TITLE
add/replace chart in the index: Invalid Semantic Version

### ISSUE THREAD

**Issue by SlavaNL** [hypnoglow/helm-s3#240]
helm version: 3.10.1
helm s3 version: 0.13/0.14

for specific chart a command `helm s3 push --force ./*.tgz repo` causes an error for all chart versions greather than `0.0.1369`. Current versions and versions below can be added/replaced successfully. Charts are identical except `appVersion` and `version` (which are equal, for example 0.0.1384) in Chart.yaml
```
add/replace chart in the index: Invalid Semantic Version
Error: plugin "s3" exited with error
```
Both "good" and "bad" versions are correct according to https://github.com/Masterminds/semver/blob/v3.1.1/version.go#L42
Reindex doesn't solve this issue

**Comment by hypnoglow** [comment]
Glob such as `./*.tgz` have never been supported by the plugin. The shell controls how the glob expands to arguments.

Which shell do you use? You can also try using something like `set -x` to see what the glob expands into.
