### ISSUE TITLE
Error installing last plugin version on windows

### ISSUE THREAD

**Issue by yul14nrc** [hypnoglow/helm-s3#247]
I am try to install the helm s3 plugin on windows 10 machine, and its returning the following error:
C:\Users\user.lastname>helm plugin install https://github.com/hypnoglow/helm-s3.git
Error: exec: "sh": executable file not found in %PATH%

**Comment by hypnoglow** [comment]
Hello

Unfortunately I don't have an access to windows machine at the moment.

It seems that your system lacks a shell. As I remember, bash and other tools come with [Git for Windows](https://git-scm.com/download/win), you can try to install it.

Alternative option is to use [WSL](https://learn.microsoft.com/en-us/windows/wsl/about).
