### ISSUE TITLE
fork/exec /home/ubuntu/.helm/plugins/helm-s3.git/bin/helm-s3 download: no such file or directory

### ISSUE THREAD

**Issue by Foxssss** [hypnoglow/helm-s3#268]
I'm using helm v2. I can init my chart repository, but can't add it to helm. What's the possible reason?

```
ubuntu@ip-10-21-15-165:~/charts-test$ helm s3 init s3://helm-charts-repository/charts-test
Initialized empty repository at s3://helm-charts-repository/charts-test
ubuntu@ip-10-21-15-165:~/charts-test$ helm repo add kasacloud s3://helm-charts-repository/charts-test
Error: Looks like "s3://helm-charts-repository/charts-test" is not a valid chart repository or cannot be reached: fork/exec /home/ubuntu/.helm/plugins/helm-s3.git/bin/helm-s3 download: no such file or directory
```

**Comment by hypnoglow** [comment]
Hello!

Is this issue still actual for you?

Could you provide a reproducible scenario?

Thanks

**Comment by Foxssss** [comment]
> Hello!
> 
> Is this issue still actual for you?
> 
> Could you provide a reproducible scenario?
> 
> Thanks

Hi,
I think maybe the release(0.14.0) I was using is not compatible with helm v2. I managed to fix this problem with an old version of release(0.6.0)

**Comment by hypnoglow** [comment]
@Foxssss helm v2 is still supported in the latest plugin release. Could you check if the error persists with the latest release?

If you could provide a reproducer (e.g. in docker container) that would be great.
