### ISSUE TITLE
Unable to install helm-s3 plugin through Github runner

### ISSUE THREAD

**Issue by hareeshgaddam** [hypnoglow/helm-s3#272]
I'm facing below error when I'm trying to install helm-s3 plugin from Github runner

`Error: Unable to get repository: fatal: could not create leading directories of '/home/runner/.cache/helm/plugins/https-github.com-hypnoglow-helm-s3.git': Permission denied`

**Comment by hypnoglow** [comment]
Could you provide more details? What is your action looks like where you are installing the plugin?

Here is the example of how the plugin is installed in GitHub Action: https://github.com/hypnoglow/helm-s3/blob/master/.github/workflows/reusable-test-install.yml. This is actually used to test that the plugin can be installed properly.
