### ISSUE TITLE
Error when install: env: can't execute 'bash': No such file or directory

### ISSUE THREAD

**Issue by myrondev** [hypnoglow/helm-s3#273]
Hi,

I want to install helm plugin by using: `helm plugin install https://github.com/hypnoglow/helm-s3.git.` I have this error:  `env: can't execute 'bash': No such file or directory`

With this command the same error: `/bin/sh -c "helm plugin install https://github.com/hypnoglow/helm-s3.git"`

**Comment by hypnoglow** [comment]
What is your context? Where do you install the plugin?

The bash is currently required to run the installation script. We might consider making it work on posix shell instead of requiring bash.

**Comment by hypnoglow** [comment]
After https://github.com/hypnoglow/helm-s3/pull/262 the bash is not required.

As the last comment states that it seems to be ok already, I'm closing this.
