### ISSUE TITLE
Support for alternative s3 endpoints (e.g. minio)

### ISSUE THREAD

**Issue by josdotso** [hypnoglow/helm-s3#29]
Any easy way to use minio instead of the real s3 with helm-s3?

https://www.minio.io/

**Comment by josdotso** [comment]
Looks like custom endpoints and disableSSL are supported only as build flags today.

https://github.com/hypnoglow/helm-s3/search?utf8=%E2%9C%93&q=awsEndpoint&type=

I would need the ability to use real S3 and minio in the same binary.  Therefore, setting these via flags and/or env vars would be ideal.  Thanks!

**Comment by hypnoglow** [comment]
Ok, I think we should provide something like `AWS_ENDPOINT` environment variable support instead of build tag.
