### ISSUE TITLE
helm s3 init failure with version 0.15.0

### ISSUE THREAD

**Issue by philturner-tsys** [hypnoglow/helm-s3#300]
Using version 0.15.0 of helm s3 plugin whilst attempting to perform helm s3 init an error is produced: couldn't load repositories file.

Output on ALIN2:
![image](https://github.com/hypnoglow/helm-s3/assets/102733302/1cf2661a-0a9f-4396-94b6-54f505275834)

After uninstalling version 0.15.0 and forcing install of version 0.14.0, output from the same command:
![image](https://github.com/hypnoglow/helm-s3/assets/102733302/cdfc68c2-19e8-48bd-b8f0-ffa4365a4799)

This looks to be a bug with version 0.15.0 - I've also reproduced the same results on a Mac.

**Comment by hypnoglow** [comment]
Thanks for reporting. I see where this issue is coming from.

Meanwhile, could you provide more context on your usage? As I understood, it is a clean helm installation and that's why there is no files in `~/.config/helm/`, am I correct?

**Comment by hypnoglow** [comment]
Was able to reproduce

```
Error: lookup repo entry by url: load repo file: Couldn't load repositories file (/root/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
Error: plugin "s3" exited with error
```

Will be fixed soon

**Comment by philturner-tsys** [comment]
> Thanks for reporting. I see where this issue is coming from.
> 
> Meanwhile, could you provide more context on your usage? As I understood, it is a clean helm installation and that's why there is no files in `~/.config/helm/`, am I correct?

I was able to reproduce the error on a helm installation that had previously successfully initialized a s3 repo using 0.14.0 afer uninstalling the 0.14.0 plugin and installing the 0.15.0 plugin.
