### ISSUE TITLE
No results found

### ISSUE THREAD

**Issue by denispeyrusaubes** [hypnoglow/helm-s3#339]
Hi,

```
> helm plugin list
NAME	VERSION	DESCRIPTION                                                                                
s3  	0.15.1 	Provides AWS S3 protocol support for charts and repos. https://github.com/hypnoglow/helm-s3
```

I have been able to to `init` a repo, Than push a chart : 

```
> helm repo list
NAME 	URL                         
myname	s3://my-s3-bucket/charts
``` 

I can check my chart in the repo using the AWS CLI: 
```
> aws s3 ls s3://com.retengr.helm/charts/
2023-12-04 21:37:01          0 
2023-12-04 22:13:26       4276 bank-1.1.0-otlp-microservice.1.tgz
2023-12-04 23:15:40        471 index.yaml
```

But searching using Helm is failing

```
> helm search repo bank
No results found
```

Any idea ?

**Comment by denispeyrusaubes** [comment]
After some test, I've identify the source of the problem 👍 
The version of my chart is `1.1.0-otlp-microservice.1`. It seems to be to complicated :) 
BTW, this version is semver compliant and should be supported no ?

**Comment by hypnoglow** [comment]
Hello! It seems that the version is valid in terms of semver, however for some reason it causes problems for `helm search`.

An option is to check the index contents and dive deeper into helm source code and check what's wrong with the index search.

I believe nothing can be done from the **helm-s3** side here.
