### ISSUE TITLE
Define custom endpoint for S3-compatible vendors

### ISSUE THREAD

**Issue by Nowaker** [hypnoglow/helm-s3#34]
There's many providers who offer an S3-compatible storage service, e.g. [DreamObjects](https://www.dreamhost.com/cloud/storage/). It would be great to allow a custom endpoint URL to be set via environment variable. Thanks!

**Comment by hypnoglow** [comment]
Hi @Nowaker ,

Today I released [v0.5.2](https://github.com/hypnoglow/helm-s3/releases/tag/v0.5.2) that allows you to do just that. See #29 

I guess I need to document this feature in README.md :roll_eyes:

**Comment by Nowaker** [comment]
Wow! Awesome. :-) Thanks!
