### ISSUE TITLE
Version required

### ISSUE THREAD

**Issue by lee5i3** [hypnoglow/helm-s3#36]
I am noticing when I am trying to install or inspect my charts it is unable to find unless I specify the verison number.

Is there no way to set the latest one as the default?

Examples:
root@SURFACE:/mnt/c/Temp# helm install myrepo/myapp --debug
[debug] Created tunnel using local port: '49901'

[debug] SERVER: "127.0.0.1:49901"

[debug] Original chart version: ""
Error: chart "myapp" matching  not found in myrepo index. (try 'helm repo update'). No chart version found for myapp-

and..

root@SURFACE:/mnt/c/Temp# helm inspect myrepo/myapp --debug
Error: chart "myapp" matching  not found in myrepo index. (try 'helm repo update'). No chart version found for myapp-

**Comment by hypnoglow** [comment]
Hi @lee5i3 !

Actually, version is not required, and without version the latest chart should be installed. I've tested it and it works for me.

This error occurs when there is no chart "myapp" in the index file. The index file is either local (already downloaded and cached) or remote. So I suggest double-checking your index, and ensure that `helm search myrepo ` finds your `myapp` chart.

If you have no success, please provide more details about your problem (helm version and helm-s3 plugin version), we will try to investigate it deeper.
