### ISSUE TITLE
Unable to install the plugin

### ISSUE THREAD

**Issue by dangarthwaite** [hypnoglow/helm-s3#38]
```
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

$ helm plugin install https://github.com/hypnoglow/helm-s3.git
Error: Unable to update checked out version
```

**Comment by hypnoglow** [comment]
Hi @dangarthwaite 

Sadly, that error message from helm is not much informative. Searching in source code for this error message shows that this error is related to Git.  

Can you double check that the plugin git working directory is clean and you can manually execute command like "git checkout v0.6.0"?

```
$ cd ~/.helm/plugins/helm-s3.git/
$ git checkout v0.6.0
```

As an option, you can try to uninstall the plugin, clean plugin cache and install from scratch:
```
$ helm plugin remove s3
$ rm -rf ~/.helm/cache/plugins/https-github.com-hypnoglow-helm-s3.git/
$ helm plugin install https://github.com/hypnoglow/helm-s3.git
```

**Comment by dangarthwaite** [comment]
It worked when I provided the version.

    helm plugin install https://github.com/hypnoglow/helm-s3.git --version
0.6.0

**Comment by beyondszine** [comment]
Hi, please do check your permissions also in the plugins folder.  I observed a few system to give this error:
```
vedakube@vedakube:~$ helm plugin install https://github.com/hypnoglow/helm-s3.git --debug=true --version 0.8.0
[debug] cloning https://github.com/hypnoglow/helm-s3.git to /home/vedakube/.helm/cache/plugins/https-github.com-hypnoglow-helm-s3.git
Error: Unable to get repository
```
It has been primarily because of user permission for the files/folder there.
