### ISSUE TITLE
Document required IAM permissions for RO and RW accesses

### ISSUE THREAD

**Issue by mvisonneau** [hypnoglow/helm-s3#42]
It would be nice to have the list of the IAM permissions required on the bucket in order to be able to `fetch`, `push` and `reindex`

**Comment by andytom** [comment]
This might not be 100% correct but the following seem to work in my testing `s3:ListBucket` and `s3:GetObject` for Read Only and `s3:ListBucket`, `s3:GetObject`,`s3:PutObject` and `s3:DeleteObject`for Read Write.
