### ISSUE TITLE
Failed to load chart file

### ISSUE THREAD

**Issue by giet12aei033** [hypnoglow/helm-s3#431]
Hi Team,

I am getting below error while performing a helm push. Could any one please helm me out?

 helm repo add test s3://xxxxxxxx/charts
 helm s3 push --force xxxxxxxx.xxx.tgz test

> Error: failed to load chart file: cannot load a directory
"test" has been added to your repositories
Error: plugin "s3" exited with error

**Comment by hypnoglow** [comment]
Hello,

There is too little information about the problem. If you could provide a reproducer that would help us diagnose the issue.

I'm going to close the issue for now, but feel free to add details, and I'll reopen if the problem exists.
