### ISSUE TITLE
add "--dry-run" option for push

### ISSUE THREAD

**Issue by jgangemi** [hypnoglow/helm-s3#44]
it would be great to be able to detect if the version of the chart as not been changed as part of PR validation instead of waiting until release.

this option would indicate if a chart upload would fail due to the version not being changed.

**Comment by hypnoglow** [comment]
Hi @jgangemi , thanks for your interest.

So, you mean, you want to check if such version already exists in the repository without triggering an error from `helm s3 push`, right?
