### ISSUE TITLE
Support for S3 bucket region

### ISSUE THREAD

**Issue by kody-abe** [hypnoglow/helm-s3#49]
Any way to support passing in the region for the bucket as sometimes we use helm with different environments than the S3 bucket for the chart repo and we get the following error:

```
fetch from s3: fetch object from s3: BucketRegionError: incorrect region, the bucket is not in 'us-west-2' region
    status code: 301, request id: , host id: 
Error: failed to download "REPO/PACKAGE" (hint: running `helm repo update` may help)
```

**Comment by hypnoglow** [comment]
Hi @kody-abe 

Have you tried `export AWS_DEFAULT_REGION=<your-region>`?

**Comment by kody-abe** [comment]
@hypnoglow Thanks for the response. The problem is that will change the region for the running helm work as well. We only need the change for just the private repo fetch.

**Comment by hypnoglow** [comment]
> The problem is that will change the region for the running helm work as well.

I don't quite get it, what do you mean by that?

Can you provide more details for your use case, please?

**Comment by kody-abe** [comment]
@hypnoglow Yeah, I got mixed up. That should work, thanks!
