### ISSUE TITLE
Feature Requests - AWS Credential profiles, Deleting charts, Reindexing repo

### ISSUE THREAD

**Issue by xyin96** [hypnoglow/helm-s3#5]
First of all, great work with this plugin, it works like a charm for us, and alleviated a lot of friction we had using a private s3 bucket for our chart repo. Here a few feature suggestions that we would love to see (if I had the time, I would love to jump in and help out):

### AWS Profiles
In my use case, my AWS `credentials` file has multiple profiles (one personal and one for work). It would be nice to see that there is an option to specify which credentials profile to use to access the bucket.

Possible usage: `helm s3 ... [--profile (default: default)]`

### Reindexing the repository
If for some reason we manually go into the s3 bucket, and modify the existing charts, I think we should have a method to easily reindex the `index.yaml` directly from the `helm` command through this plugin

Possible usage: `helm s3 reindex [repo]`

### Deleting charts from the repository
I think that there should be a method to delete charts from the repo, and regenerate the `index.yaml` to reflect that.

Possible usage: `helm s3 delete [chartName] [repo] [--version (default: latest)]`.

**Comment by hypnoglow** [comment]
Thank you. These are definitely interesting suggestions. I am going to take some time to investigate.

**Comment by hypnoglow** [comment]
Closing this issue, because AWS profiles and deleting charts features were implemented in #7 and #10, and the reindexing is on the way #22

Thanks again for raising the ideas!
