### ISSUE TITLE
Traverse the chart repository: load archive from s3 object: EOF

### ISSUE THREAD

**Issue by kylehodgetts** [hypnoglow/helm-s3#57]
Helm s3 version: 0.7.0

When trying to index to index my repo I get the following message:

`traverse the chart repository: load archive from s3 object: EOF`

I am logged in and have all permissions for s3

**Comment by kylehodgetts** [comment]
Fixed this issue myself. But I'm leaving this issue open.
The problem was having another type of file in the repository other than `.yaml` and `.tgz`

When reindexing, surely this plugin should just ignore other files?

I guess this would be open to discussion

**Comment by hypnoglow** [comment]
Thanks for raising this. Yeah, this has been there since reindex introduction: https://github.com/hypnoglow/helm-s3/issues/22#issuecomment-356408598

I think taking into account only `*.tgz` files is fine. As far as I know, a packaged chart is **always** a `*.tgz` file, correct me if I'm wrong.

**Comment by kylehodgetts** [comment]
Yes it is. I've never come across another type of chart archive
