### ISSUE TITLE
Error: unknown command "s3" for "helm"

### ISSUE THREAD

**Issue by sagarkal** [hypnoglow/helm-s3#61]
When I installed helm-s3 and tried to push to S3, it fails with the below error
```
$ helm s3 push --force "./abc-$(./version)-${CI_COMMIT_REF_NAME:0:11}-${CI_COMMIT_SHA:0:8}.tgz" "<repo_name>"
Error: unknown command "s3" for "helm"
Run 'helm --help' for usage.
```

**Comment by hypnoglow** [comment]
Hi,

How did you install the plugin? What is the version of helm? Did you change any helm-related default paths, like `HELM_HOME`?

Any other details would be helpful too. Thanks.

**Comment by sagarkal** [comment]
Hello,

I got this error while setting up a Gitlab runner as shell executor. But then I configured it as a docker executor as a workaround for this problem.
