### ISSUE TITLE
Make is a Dependency but the docs don't state this 

### ISSUE THREAD

**Issue by willhayslett** [hypnoglow/helm-s3#62]
Hi, 

Just a small issue. The docs state: 

> To use the plugin, you do not need any special dependencies.

The semantics of "special" may be debated here, but we encountered errors installing this plugin in an Ubuntu image because it did not `make`. It may help to list out in the docs that you do actually need the `make` utility. 

Thanks!

**Comment by hypnoglow** [comment]
Hi,

Nice catch, thanks! `make` is a dependency indeed. However, we can avoid this dependency and configure **plugin.yaml** file just to execute `./hack/install.sh` directly. What do you think?

**Comment by willhayslett** [comment]
I think that makes sense. PR sent for the changes.
