### ISSUE TITLE
Unable to use AWS_PROFILE with credential_source configuration

### ISSUE THREAD

**Issue by sdavids13** [hypnoglow/helm-s3#69]
When using the standard AWS CLI profile defined as:
```
[helm-chart-uploader]
role_arn = arn:aws:iam::#########:role/MyUploaderRole
credential_source = Ec2InstanceMetadata
```

I am able to upload artifacts as the cross-account user via the AWS CLI (`AWS_PROFILE=helm-chart-uploader`), but when running the `helm s3 push` command it seems to ignore the AWS_PROFILE value and not upload as the expected assumed role. If the AWS_PROFILE functionality is being delegated to the Go SDK that capability was added via https://github.com/aws/aws-sdk-go/pull/2201 (which is in v1.15.54+ -- latest patch release being v1.15.89)

**Comment by hypnoglow** [comment]
This issue should be solved by #74 (which will go into the next release of the plugin). If it is not, please open the new issue and we will revisit this.
