### ISSUE TITLE
access denied error despite setting AWS credentials

### ISSUE THREAD

**Issue by mohammadasim** [hypnoglow/helm-s3#75]
Helm version: 2.14.1
plugin version: 0.8.0
I have installed helm and helm-s3 plugin on our Jenkins server. I want to build Jenkins pipeline that will package and push our helm charts to our helm repo in AWS.  The Jenkins server has an IAM role with a policy allowing all s3 actions on the s3 bucket holding our helm repo.  On the commandline I can list and put-object to the s3 bucket.
`$ aws s3 ls 123456789-helm-bucket`
                           `PRE my-charts/`
However, when I try to add this repo to the helm, I get access denied error.
`helm repo add my-charts s3://123456789-helm-bucket/my-charts
fetch from s3: fetch object from s3: AccessDenied: Access Denied
	status code: 403, request id: C641C8B8F9131614, host id: Tnu5Cu+iI+WqOoiTlousoefgn5Dfr8rKOzqY+mpebDpHPfDwKJn9JQ5xoTNBvKPfc5uHpouRchU=
Error: Looks like "s3://123456789-helm-bucket/my-charts" is not a valid chart repository or cannot be reached: plugin "bin/helms3" exited with error`
I have tried to run aws configure command and added credentials and also tried by setting AWS_ACCESS_KEY, AW_SECRET_KEY and AWS_REGION variables as well, but each time I get the same error.

**Comment by mohammadasim** [comment]
Thanks for your reference. But my issue is not with cross-account. The IAM role and the AWS credentials created are for the same account where the s3 bucket containing the helm repo has been created.

**Comment by mohammadasim** [comment]
Further investigation revealed that the issue was with AWS policy that defined the level of access.

**Comment by rajivchirania** [comment]
@mohammadasim Can you please tell me what kind of issue with AWS policy..

**Comment by mohammadasim** [comment]
The problem that I had was that the policy document in AWS didn't have the correct permissions and when I changed the permissions on the AWS policy that I had created for the IAM user, it fixed the problem.

**Comment by rajivchirania** [comment]
@mohammadasim however i have the proper policy set and it works when i use helm 2.13.0 however if i update the helm then it doesnt work...also using the latest version of helm-s3 plugin..

**Comment by mohammadasim** [comment]
As a test give your policy admin access and check if it will work then the issue is with permissions if not then you have a problem elsewhere. For reference, I am using helm3 with the latest helm-s3 plugin and I haven't experienced any problems.

**Comment by rajivchirania** [comment]
@mohammadasim the role has admin policy attach who is try to access the  chart repo however i think something with cross account doesnt work properly..

**Comment by rvfn** [comment]
Yeah, can anyone explain why when using helm3 this plugin doesn't work cross account, but on helm2 it works perfectly?  That has me absolutely baffled

**Comment by AndrewFarley** [comment]
I'm seeing what @rajivchirania sees above, when using helm2 this cross-account works fine, can publish and use a s3 bucket, but from helm3 I can not.  What gives?  :P

**Comment by AndrewFarley** [comment]
^ Nevermind, worked out my issue.  See: https://github.com/hypnoglow/helm-s3/issues/72#issuecomment-692442570
