### ISSUE TITLE
Getting MissionRegion when trying to run "helm repo add"

### ISSUE THREAD

**Issue by saokar** [hypnoglow/helm-s3#76]
Running this command
helm repo add my-helm-repo  "s3://<my-bucket-name>"

getting the following error,
**fetch from s3: fetch object from s3: MissingRegion: could not find region configuration**

How do I specify the S3 region? I am running this in a docker container

**Comment by mforutan-flexera** [comment]
you can include the region in the command

> $ AWS_REGION=us-east-1 helm repo add my-helm-repo "s3://"

**Comment by hypnoglow** [comment]
I believe the problems with region are currently solved, as documented in [README](https://github.com/hypnoglow/helm-s3#s3-bucket-location), thus I'm going to close this issue.
