### ISSUE TITLE
_helm s3 init_ message is missing a slash

### ISSUE THREAD

**Issue by horacimacias** [hypnoglow/helm-s3#77]
When using an s3 bucket without index.yaml, the error message states:

_The index file does not exist by the path s3://bucketname/index.yaml. If you haven't initialized the repository yet, try running "helm s3 init s3:/bucketname"_

That is missing a slash after "s3:/". If you run the command as is you'll get:

_upload index to s3: uri s3:/bucketname/index.yaml protocol is not s3_

The error message needs to have a double slash after s3:

**Comment by horacimacias** [comment]
Created https://github.com/hypnoglow/helm-s3/pull/78

**Comment by hypnoglow** [comment]
Fixed in #78 , thanks @horacimacias
