### ISSUE TITLE
`helm repo add` on an s3 bucket in different region does not work

### ISSUE THREAD

**Issue by schollii** [hypnoglow/helm-s3#83]
This may not be a bug, maybe I'm missing some setting but I can't find how to make helm use a repo in a different region from the default set in my AWS profile. Here is my `.aws/config` file:
```
[profile-us-east-1]
region = us-east-1

[profile-us-west-2]
region = us-west-2
```
The helm s3 repo `s3://mybucket-in-us-east-1/helm-charts-repo` is in us-east-1. The following works:
```
$ export AWS_PROFILE=profile-us-east-1
$ helm repo add myrepo s3://mybucket-in-us-east-1/helm-charts-repo
"myrepo" has been added to your repositories
```
Now change the profile default region: 
```
$ helm repo remove myrepo
"myrepo" has been removed from your repositories
$ export AWS_PROFILE=profile-us-west-2
$ helm repo add myrepo s3://mybucket-in-us-east-1/helm-charts-repo
fetch from s3: fetch object from s3: BucketRegionError: incorrect region, the bucket is not in 'us-west-2' region
	status code: 301, request id: , host id: 
Error: Looks like "s3://mybucket-in-us-east-1/helm-charts-repo" is not a valid chart repository or cannot be reached: plugin "bin/helms3" exited with error
```

What am I doing wrong?

**Comment by schollii** [comment]
Workaround: 

```
AWS_REGION=us-east-1 helm repo add myrepo s3://mybucket-in-us-east-1/helm-charts-repo
```

**Comment by hypnoglow** [comment]
Hi,

I repeated your steps without `AWS_REGION=us-east-1` workaround and everything worked fine. First I thought about "outdated" aws sdk dependency which was updated in #74, but I checked on both v0.8.0 and master branch and they both worked for me.

Note that in `.aws/config` file you have to prefix profile names with the word **profile** as stated in https://docs.aws.amazon.com/en_us/cli/latest/userguide/cli-configure-profiles.html

```
[profile frankfurt]
region = eu-central-1

[profile london]
region = eu-west-2
```

This may resolve your issue.

I'm going to close this. If you still experience the issue, please leave a comment and I will reopen it to investigate further.
