### ISSUE TITLE
Terraform support

### ISSUE THREAD

**Issue by amitaymolko** [hypnoglow/helm-s3#84]
Would be great to get this to work in Terraform.
Helm repo for terraform exists: https://www.terraform.io/docs/providers/helm/repository.html

**Comment by bluemalkin** [comment]
You will just need to install the plugin and you're good to use https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release

**Comment by amitaymolko** [comment]
Hello,
At the time it didn't work with the helm TerraForm plugin.
The s3:// urls weren't working as the repository. 
Were you able to get it working?

**Comment by bluemalkin** [comment]
@amitaymolko  yes no issues.

Note that the resource https://registry.terraform.io/providers/hashicorp/helm/latest/docs/data-sources/repository is being deprecated.

I reference the s3:// directly like this:

```
resource "helm_release" "test" {
  name       = "test"
  repository = "s3://BUCKET"
  chart      = "my-chart"
  version    = "0.1.0"
}
```

Just make sure your AWS credentials are setup properly. For example if you're using a profile, you'll need to set an ENV var `AWS_PROFILE=NAME`

**Comment by amitaymolko** [comment]
ok I'll close this issue, thanks!
