### ISSUE TITLE
Helm v3 macOS how do I point to the correct repo file

### ISSUE THREAD

**Issue by demo-ecout** [hypnoglow/helm-s3#91]
helm env
`HELM_BIN="helm" 
HELM_DEBUG="false" 
HELM_PLUGINS="/Users/user/Library/helm/plugins" 
HELM_REGISTRY_CONFIG="/Users/user/Library/Preferences/helm/registry.json" 
HELM_REPOSITORY_CACHE="/Users/user/Library/Caches/helm/repository" 
HELM_REPOSITORY_CONFIG="/Users/user/Library/Preferences/helm/repositories.yaml" `

helm s3 reindex my repo
load repo file: open /Users/user/.helm/repository/repositories.yaml: no such file or directory

The bug seems to be here:
https://github.com/hypnoglow/helm-s3/blob/master/internal/helmutil/repo_entry.go

Now my env var HELM HOME is empty 

`echo $HELM_HOME

` 

but if I populate in the session and force it to fail

`
export HELM_HOME=/Users/user/Library/Caches/helm/repository/`

`
 helm s3 reindex boingodev
load repo file: open /Users/user/Library/Caches/helm/repository/repository/repositories.yaml: no such file or directory
`

So the code is assuming the /repository/repositories.yaml subfolder always exists. Which is not the case for me.

Q:Why are you using the OS environment variables instead of the helm's internal configuration?
A: the env parameter is not supported on 2.x but only on 3.x which just became stable recently.

**Comment by demo-ecout** [comment]
These are the defaults for Helm v3:

+------------------+---------------------------+--------------------------------+-------------------------+
| Operating System | Cache Path                | Configuration Path             | Data Path               |
+------------------+---------------------------+--------------------------------+-------------------------+
| Linux            | $HOME/.cache/helm         | $HOME/.config/helm             | $HOME/.local/share/helm |
| macOS            | $HOME/Library/Caches/helm | $HOME/Library/Preferences/helm | $HOME/Library/helm      |
| Windows          | %TEMP%\helm               | %APPDATA%\helm                 | %APPDATA%\helm          |
+------------------+---------------------------+--------------------------------+-------------------------+

**Comment by demo-ecout** [comment]
If I add the repo with the following arguments

`helm repo add boingodev s3://chart-repo-x/charts --registry-config /Users/user/.helm/registry.json --repository-cache  /Users/user/.helm/repository/cache --repository-config  /Users/user/.helm/repository/repositories.yaml`

I get a new error:
helm s3 reindex boingodev
load repo file: error unmarshaling JSON: json: cannot unmarshal array into Go value of type string
Error: plugin "s3" exited with error

**Comment by jwalton** [comment]
I'm running into the same problem.  I created a new s3 repo:

```
helm s3 init s3://mybucket/helm
helm repo add mybucket s3://mybucket/helm
```

Then I tried to push something to this bucket:

```
$ helm s3 push reporting-2.0.15.tgz mybucket
load repo file: open /Users/jwalton/.helm/repository/repositories.yaml: no such file or directory
Error: plugin "s3" exited with error
```

My ~/.helm doesn't exist.  The correct location, as @demo-ecout notes above, is ~/Library/Preferences/helm/repositories.yaml.

**Comment by mohammadasim** [comment]
I updated from helm2 to helm3 using the official migration blog and the official 2to3 plugin. As part of the migration at the end .helm folder was completely deleted. Now When I try to push anything to my helm repo in S3 I get error pointing to repositories.yml file in `.helm/repository/respositories.yml`. Is there anyway I can update the location of this file?

**Comment by hypnoglow** [comment]
Helm v3 support is WIP, we plan to add this into the next plugin release.

**Comment by hypnoglow** [comment]
Version [0.9.0](https://github.com/hypnoglow/helm-s3/blob/master/CHANGELOG.md#090---2019-12-27) is now released with Helm v3 support, please try! 

This issue should be fixed, please open a new issue if something does not work as expected. Thanks.

**Comment by ecout** [comment]
Thanks @hypnoglow will continue to test.

**Comment by jwalton** [comment]
Yes, many thanks @hypnoglow!  It's working for me!
