### ISSUE TITLE
cut a new release

### ISSUE THREAD

**Issue by willejs** [hypnoglow/helm-s3#93]
Its not very easy atall to use the new changes until a new release has been built and published. Can you cut a new release please?

**Comment by hypnoglow** [comment]
Hi, sorry for the inconvenience. The work is ongoing, we plan to add some improvements like helm v3 support before the new plugin release.

**Comment by rplute** [comment]
Hi, @hypnoglow , thanks for all your hard work! Do you know when the release with helm v3 support will be available?

**Comment by hypnoglow** [comment]
Most of the work is complete, but we need some regression testing to do. If everything goes fine, I suppose we release it by the next week.

**Comment by hypnoglow** [comment]
Version [0.9.0](https://github.com/hypnoglow/helm-s3/blob/master/CHANGELOG.md#090---2019-12-27) is now released, sorry for delays and thank you very much for patience ❤️
