### ISSUE TITLE
Can list the s3 repo but not interact

### ISSUE THREAD

**Issue by DavidGoodfellow** [hypnoglow/helm-s3#94]
Hello, when I try and use an s3 bucket as my helm repo, I can see that it is one of my repos. However, when I go ahead and try to interact with it in anyway (reindex, push a chart, etc.) it says that the repo does not exist. Do you know what might be causing this? Below is some of the terminal output and different configurations I have.

(base) C:good$ helm s3 init s3://helm-test-charts/
Initialized empty repository at s3://helm-test-charts/
(base) C: good$ helm repo add myrepo s3://helm-test-charts/
"myrepo" has been added to your repositories
(base) C: good$ helm search repo myrepo
No results found
(base) C: good$ helm repo list
NAME     	URL                                                        
stable   	https://kubernetes-charts.storage.googleapis.com/          
incubator	https://kubernetes-charts-incubator.storage.googleapis.com/
myrepo   	s3://helm-test-charts/  
helm s3 push ./test-chart9-0.1.0.tgz myrepo
repo with name myrepo not found, try `helm repo add myrepo <uri>`
Error: plugin "s3" exited with error
(base) C: good$ helm s3 reindex myrepo
repo with name myrepo not found, try `helm repo add myrepo <uri>`
Error: plugin "s3" exited with error

Configs:
helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
helm-s3.git --version 0.7.0

**Comment by hypnoglow** [comment]
Helm v3 support is WIP, we plan to add this into the next plugin release.

**Comment by hypnoglow** [comment]
Version [0.9.0](https://github.com/hypnoglow/helm-s3/blob/master/CHANGELOG.md#090---2019-12-27) is now released with Helm v3 support, please try! 

This issue should be fixed, please open a new issue if something does not work as expected. Thanks.
