### ISSUE TITLE
helm s3 reindex throws error

### ISSUE THREAD

**Issue by benejo** [hypnoglow/helm-s3#96]
I did s3 sync of helm repo bucket to another bucket(disaster recovery region). The idea is to copy chart zips to DR bucket and setup that bucket as a new S3 repo for DR region.
When running "helm s3 reindex repo-name" I get the following error,

```
traverse the chart repository: unserialize chart meta: invalid character '=' looking for beginning of value
Error: plugin "s3" exited with error
```

helm client version: v2.11.0
helm s3 version: 0.8.0

**Comment by premkumar-gg** [comment]
Happens for us too.. this is especially after the "hazelcast" chart was included in our repository. Did you get to resolve this?

**Comment by mstrejczek** [comment]
I've just seen it too.
```
helm plugin list
NAME      	VERSION	DESCRIPTION                                                                                
nexus-push	0.0.1  	Pushes a chart directory or packaged chart tgz to a specified repo,                        
          	       	either by named repo ...                                                                   
s3        	0.9.2  	The plugin allows to use s3 protocol to upload, fetch charts and to work with repositori...

```

**Comment by ILunie** [comment]
do you already have a solution to this?

**Comment by hypnoglow** [comment]
I believe this should be fixed already. Please try using the latest plugin release.

I'm going to close this issue, feel free to reach out again if you still experience the problem, and please provide the `Chart.yaml` file.

**Comment by Shion1305** [comment]
I was getting the same error, and this was because of #461 .
